### ISSUE TITLE
Short term work plan

### ISSUE THREAD

**Issue by ocmadin** [ramess101/RJMC_LJ_Ethane#5]
- [ ] Improve model swap acceptance for the 'All' cases

In general, model swap acceptance ratios are lower for 'All' cases than they are for 'rhol+psat' cases.  We should look at using better Q proposals, model mapping techniques, and swap frequencies to improve these ratios - they will probably be different for different compounds

- [ ] Run 10^7 step RJMC for all compounds in the 'rhol+Psat' case.

Currently completed: 
- C2H6 (Bayes Factor = 2.8)
- N2 (Bayes Factor = 2.4)
- O2 (Bayes Factor = 8.0)

Todo:
- C2H2 (Good data coverage except for SurfTens, only coverage from 0.62Tc-0.7Tc)
- C2H4 (Good data coverage except for SurfTens, only coverage from 0.41Tc-0.65Tc)
- Br2 (Good data coverage except for SurfTens, only coverage from 0.47Tc-0.55Tc)
- Cl2 (Only Psat data available)
- C2F4 (Good data coverage except for SurfTens, No SurfTens data available)
- C2Cl4 (rhol and Psat data only from 0.4Tc-0.65Tc, no SurfTense data available)
- F2 (Good Psat data coverage, rhol only from 0.5Tc-0.6Tc, SurfTens only from 0.45Tc-0.55Tc)

- [ ] Run 10^7 step RJMC for selected compounds in the 'All' case

- Have completed simulations for C2H6, N2, but unsure if results are valid (100% model 0 sampling for N2, uncoverged distribution for C2H6)
- Will run for O2 in the near future
- Won't be possible to do this for Cl2,C2F4,C2Cl4
- Will be able to do with modified data ranges for C2H2,C2H4,Br2,F2

This is a relatively short term plan, after completing these tasks and looking at the distributions/Bayes factors, we can determine how to move forward. If there are things you think I am missing please let me know.

@ramess101

**Comment by ramess101** [comment]
This is a good start. A few ideas I would like to consider:

1) Toy problems where we generate data from:
   a) 3 parameter model with different degrees of scatter
   b) Conflicting data sets from different underlying parameter sets

2) Include the 1, 2 parameter models (simultaneous sampling/comparison of 4
models)

3) Include 3 parameter model where parameters are eps, sig, and Q

4) Sensitivity to error model, data ranges, amount of data, etc (could use
toy problems for this)
